# Generated by Django 2.1 on 2020-01-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crd', models.DateTimeField(auto_now_add=True, null=True)),
                ('upd', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crd', models.DateTimeField(auto_now_add=True, null=True)),
                ('upd', models.DateTimeField(auto_now=True, null=True)),
                ('book_name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='books.Category')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
